name: docStore
services:
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "8000:5000"
    volumes:
      - ./backend/:/usr/src/app
    env_file:
      - .env
    depends_on:
      - database

  database:
    platform: linux/amd64
    container_name: database
    image: mcr.microsoft.com/mssql/server:2025-latest
    ports:
      - "1433:1433"
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=Docstore12345"

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "8001:4200"
    volumes:
      - ./frontend/:/usr/src/app
      - frontend_node_modules:/usr/src/app/node_modules

volumes:
  frontend_node_modules:
  
